Id: Sublime.Sublime3
Version: 0.73
Name: Sublime
Publisher: Sublime
Homepage: https://www.sublimehq.com
License: (c) Sublime HQ Pty Ltd
Description: A sophisticated cross-platform text editor for code, markup and prose.
Installers: 
    - Arch: x86
      Url: https://download.sublimetext.com/Sublime%20Text%20Build%203211%20Setup.exe
      InstallerType: Inno
      Sha256: 72350BE01792FEABF1C13F66DCA8FE57C65EE16DE90A2345D135A38C8A8A670B
