# Automatically updated by the winget bot at 2021/May/05
ï»¿PackageIdentifier: Amazon.AWSCLI
Publisher: AWS
PackageName: AWS Command Line Interface v1
PackageVersion: 1.19.66
License: Copyright 2012-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved. Licensed under the Apache License, Version 2.0
LicenseUrl: https://github.com/aws/aws-cli/blob/1.18.214/LICENSE.txt
Author: Amazon Web Services
Moniker: aws
Tags:
- cli
- aws
- amazon
ShortDescription: Universal Command Line Interface for Amazon Web Services
PackageUrl: https://aws.amazon.com/cli/
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi
  InstallerSha256: A8B6077B281D067CECE8EC3A56FF60D30F6A60A749282679EDB88C5CDBEB278C
  ProductCode: "{1C96DE4D-A969-4067-8E2C-0473F22800B7}"
  InstallerSwitches:
    Silent: /quiet /norestart
    SilentWithProgress: /passive /norestart
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
